# Spec file for GitDeck
# Do not edit this file manually - it's updated by CI/CD

Name:       harbour-gitdeck
Summary:    Native GitHub client for Sailfish OS
Version:    0.1.0
Release:    1
Group:      Applications/Internet
License:    GPLv3
URL:        https://github.com/yourusername/harbour-gitdeck
Source0:    %{name}-%{version}.tar.bz2

Requires:   sailfishsilica-qt5 >= 1.0.0

BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  desktop-file-utils

%description
GitDeck is a native GitHub client for Sailfish OS that provides
full access to your GitHub repositories with a native UI experience.

Features:
- GitHub Actions monitoring with detailed step information
- Release management with asset downloads
- Issues and Pull Requests
- Repository browsing (files, commits, branches)
- OAuth 2.0 and Personal Access Token authentication
- Native Sailfish UI


%prep
%setup -q -n %{name}-%{version}

%build
%qmake5 harbour-gitdeck.pro

make %{?_smp_mflags}

%install
rm -rf %{buildroot}
%qmake5_install

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
